# Generated by Django 4.2.11 on 2024-06-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_remove_trainerprofile_customers_and_more'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='trainer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.trainerprofile'),
        ),
    ]
