# Generated by Django 4.2.11 on 2024-06-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerprofile_routines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(default='users/user_image.png', upload_to='users/'),
        ),
    ]
