# Generated by Django 4.2.11 on 2024-06-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
