# Generated by Django 4.2.11 on 2024-06-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('customer', '0001_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='routines',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='routines.routine'),
        ),
    ]
