# Generated by Django 4.2.11 on 2024-06-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_trainerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
