# Generated by Django 4.2.11 on 2024-06-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customerprofile_profile_picture'),
        ('trainer', '0005_trainerprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='customers',
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='customer.customerprofile'),
        ),
    ]
