# Generated by Django 4.2.11 on 2024-06-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customerprofile_profile_picture'),
        ('trainer', '0006_remove_trainerprofile_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='customers',
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='customer.customerprofile'),
        ),
    ]
