# Generated by Django 4.2.11 on 2024-06-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_trainerprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='routines',
        ),
    ]
