# Generated by Django 4.2.11 on 2024-06-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(max_length=100)),
                ('image', models.ImageField(default='exercise_image.png', upload_to='exercises/')),
                ('youtube_link', models.URLField(blank=True)),
            ],
        ),
    ]
